


INSERT INTO REFCOMERCIAL.DBO.infoINSS
(
    FECHA_BASE,
    NO_INSS,
    NOMBRE,
    CEDULA,
    EMPRESA,
    DOMI_EMP,
    SALARIO,
    EMPLEADOR,
    NOMINA,
    DOMI_ASE,
    disponible
)
SELECT 
GETDATE(),
A.INSS,
REPLACE(REPLACE(CONCAT(NOMBRE1,SPACE(1),NOMBRE2,SPACE(1),APELLIDO1,SPACE(1),APELLIDO2),'NULL',''),'  ',' ') COLLATE DATABASE_DEFAULT AS NOMBRE,
CEDULA COLLATE DATABASE_DEFAULT,
EMPRESA COLLATE DATABASE_DEFAULT,
DOMICILIO_EMP  COLLATE DATABASE_DEFAULT,
SALARIO,
EMPLEADOR,
NOMINA,
DOMICILIO_ASE COLLATE DATABASE_DEFAULT,
1
FROM BASESRECIBIDAS.DBO.db_inss_29062019_1 A
