

select
*
 from BaseCallbacksFiltrada 
where 
CITY IN ('CARAZO','RIVAS','GRANADA/','MANAGUA.')
AND 
city NOT in(
'CHINANDEGA',
'LEON',
'MASAYA',
'GRANADA','MANAGUA',
'ESTELI','MADRIZ','JINOTEGA',
'CHONTALES','BOACO','MATAGALPA'
)