WITH CTE_BASE
AS (
    SELECT LTRIM(RTRIM(STR(NUM_TELEFONO_OTRO,8))) AS Telefono,DEPARTAMENTO,CIUDAD 
    FROM JOHNNY_BASE_IX_AGOSTO_2019 A 
),
CTE_ALLREDY_CALLED
AS(
    SELECT * FROM EFNI.DBO.Telefono A
    WHERE A.FechaLlamada >= DATEADD(MONTH,-3,GETDATE())
    OR Tipificacion = 'NAPOL'
),
CTE_ACTIVOS
AS(
    SELECT A.*,
    SUBSTRING(A.Telefono,1,4) AS PREFIJO
    FROM CTE_BASE A
    LEFT JOIN CTE_ALLREDY_CALLED B ON A.Telefono = B.EFNI_Telefono 
    WHERE B.EFNI_Telefono IS NULL
),
CTE_FILTRADA
AS(
    SELECT A.Telefono,A.DEPARTAMENTO,A.CIUDAD,B.Operadora, 
    ROW_NUMBER() OVER(PARTITION BY DEPARTAMENTO,Operadora ORDER BY DEPARTAMENTO,Operadora) N
    FROM CTE_ACTIVOS A
    LEFT JOIN GOLKIIDATA.DBO.PREFIJOS B ON A.PREFIJO = B.Prefijo
)
SELECT MAX(N) N,DEPARTAMENTO,Operadora FROM CTE_FILTRADA GROUP BY DEPARTAMENTO,Operadora ORDER BY DEPARTAMENTO


