WITH CTE_BASE
AS (
    SELECT 
        RTRIM(LTRIM(NOMBRE)) COLLATE DATABASE_DEFAULT AS NOMBRE,
        RTRIM(LTRIM(REPLACE(CEDULA,'-',''))) COLLATE DATABASE_DEFAULT AS CEDULA,
        [TEL#1] AS TELEFONO,
        PRODUCTO COLLATE DATABASE_DEFAULT AS TTARJETA
    FROM BasesRecibidas.DBO.BASE_BANPRO_NO3_15082019
),
CTE_BASE_NUEVA
AS (
    SELECT A.*,SUBSTRING(A.CEDULA,1,3) AS DEMOGRAFIA FROM CTE_BASE A
    LEFT JOIN BasesRecibidas.DBO.db_banpro_corregida_03072019 B ON A.TELEFONO = B.[TEL#1]
    LEFT JOIN BasesRecibidas.DBO.BaseBanpro2_25072019 C ON A.TELEFONO = C.[TEL#1]
    WHERE B.[TEL#1] IS NULL AND C.[TEL#1] IS NULL
),
CTE_DATA
AS(
    SELECT A.*,B.Municipio,C.Departamento,C.IdDepartamento FROM CTE_BASE_NUEVA A
    LEFT JOIN GOLKIIDATA.DBO.Municipio B ON A.DEMOGRAFIA  = B.CODIGO
    LEFT JOIN GOLKIIDATA.DBO.Departamento C ON B.IdDepartamento = C.IdDepartamento
    WHERE A.TELEFONO  LIKE '[5-8]%'
)
SELECT Departamento, COUNT(TELEFONO) AS [NO]
FROM CTE_DATA 
WHERE DEPARTAMENTO NOT IN ('LEON','CHINANDEGA','MATAGALPA','JINOTEGA','ESTELI','Masaya','Granada','Carazo','Rivas','Boaco','Chontales',
'Managua','Rio San Juan')
GROUP BY IdDepartamento,Departamento
ORDER BY IdDepartamento

-- SELECT DISTINCT A.NOMBRE,A.CEDULA,A.TELEFONO,A.TTARJETA,A.Municipio,A.Departamento--,B.Salario
-- FROM CTE_DATA A
-- WHERE
-- DEPARTAMENTO IN ('Rio San Juan') 
-- AND
-- DEPARTAMENTO NOT IN ('LEON','CHINANDEGA','MATAGALPA','JINOTEGA','ESTELI','Masaya','Granada','Carazo','Rivas','Boaco','Chontales'
-- ,'Managua'
-- )
-- ORDER BY CEDULA ASC OFFSET 1000 ROWS FETCH NEXT 2000 ROWS ONLY -- ONLY MANAGUA
