USE GOLKIIDATA_2
GO
CREATE FUNCTION ObtenerEdad
(
    @Cedula AS VARCHAR(MAX)
)
RETURNS INT
AS
BEGIN
    IF(@Cedula IS NULL OR @Cedula NOT LIKE '[0-9][0-9][0-9][0,1][0,1,2,3,4,5,6,7,8][0,1][0-9][0-9][0-9][0-9][0-9][0-9][0-9][A-Z]') 
    BEGIN 
        RETURN 0 
    END
    
    DECLARE @YEAR AS INT, @AYEAR AS INT, @IDATE AS DATE, @DATE AS DATE, @DS AS VARCHAR(MAX);
    SET @DATE = GETDATE();
    
    SET @YEAR = CAST(SUBSTRING(@Cedula,8,2) AS INT); SET  @IDATE = GETDATE();
    SET @YEAR = CASE WHEN @YEAR BETWEEN 0 AND CAST(SUBSTRING(CONVERT(VARCHAR,@DATE,112),3,2) AS INT) THEN 2000+@YEAR ELSE 1900+@YEAR END;

    SET @DS = CONCAT(@YEAR,'-',SUBSTRING(@Cedula,6,2),'-',SUBSTRING(@Cedula,4,2));
    IF(@DS NOT LIKE '[1,2][0,9][0-9][0-9]-[0,1,2][0-9]-[0-9][0-9]')
    BEGIN
        RETURN 0;
    END
    ELSE
    BEGIN
        SET @IDATE = CAST(@DS AS DATE);
    END
    RETURN FLOOR(DATEDIFF(DAY,@IDATE,GETDATE())/365)
END