-- Create a new database called 'GOLKII_KNOWLEDGE'
-- Connect to the 'master' database to run this snippet
USE master
GO
-- Create the new database if it does not exist already
IF NOT EXISTS (
    SELECT [name]
        FROM sys.databases
        WHERE [name] = N'GOLKII_KNOWLEDGE'
)
    CREATE DATABASE GOLKII_KNOWLEDGE
ELSE
BEGIN 
    ALTER DATABASE GOLKII_KNOWLEDGE SET SINGLE_USER WITH ROLLBACK IMMEDIATE
    DROP DATABASE GOLKII_KNOWLEDGE
    CREATE DATABASE GOLKII_KNOWLEDGE
END
GO
USE GOLKII_KNOWLEDGE
GO
-- DEFAULT SCHEMA DBO
-- ANOTHER SCHEMA
CREATE SCHEMA NIC
GO
CREATE SCHEMA VICI
GO
CREATE TABLE 
DBO.COUNTRY
(
	ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	[NAME] NVARCHAR(30) NOT NULL,
	ACRONYM NVARCHAR(2) NOT NULL
)
CREATE TABLE 
DBO.DEPARTMENT -- STATE OR DEPARMENT
(
	ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    COUNTRY INT FOREIGN KEY REFERENCES DBO.COUNTRY(ID) NOT NULL,
	[NAME] NVARCHAR(30) NOT NULL,
	ACRONYM NVARCHAR(2) NOT NULL
)
CREATE TABLE 
DBO.CITY
(
	ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    DEPARTMENT INT FOREIGN KEY REFERENCES DBO.DEPARTMENT(ID) NOT NULL,
	[NAME] NVARCHAR(30) NOT NULL,
	ACRONYM NVARCHAR(2) NOT NULL
)
CREATE TABLE 
DBO.CLIENT
(
    ID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
    FULL_NAME NVARCHAR(100) NOT NULL,
    FIRST_NAME NVARCHAR(25) NULL,
    MIDDLE_NAME NVARCHAR(25) NULL,
    LASTNAME_1 NVARCHAR(25) NULL,
    LASTNAME_2 NVARCHAR(25) NULL,
    [ADDRESS] NVARCHAR(255),
    MONEY_INCOME MONEY CHECK (MONEY_INCOME >= 0),
    PERSONAL_ID CHAR(50) DEFAULT NULL,
    GENDER CHAR(1) DEFAULT 'U', -- U- UNDEFINED, F- FEMALE, M- MALE
    AGE INT DEFAULT 0,
    EMAIL NVARCHAR(60),
    COUNTRY INT FOREIGN KEY REFERENCES DBO.COUNTRY(ID) NOT NULL,
    DEPARTMENT INT FOREIGN KEY REFERENCES DBO.DEPARTMENT(ID) DEFAULT NULL,
    CITY INT FOREIGN KEY REFERENCES DBO.CITY(ID) DEFAULT NULL,
    BASERECIBIDA_NAME NVARCHAR(255),
    BASERECIBIDA_ID INT,
    LAST_UPDATE DATETIME DEFAULT GETDATE(),
    WHO_DO CHAR(100) NOT NULL -- USER WHO DO LAST MODIFICATION
)
CREATE TABLE 
DBO.CLIENT_LOG
(
    ID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
    CLIENT INT FOREIGN KEY REFERENCES DBO.CLIENT(ID) NOT NULL,
    FULL_NAME NVARCHAR(100) NOT NULL,
    FIRST_NAME NVARCHAR(25) NULL,
    MIDDLE_NAME NVARCHAR(25) NULL,
    LASTNAME_1 NVARCHAR(25) NULL,
    LASTNAME_2 NVARCHAR(25) NULL,
    [ADDRESS] NVARCHAR(255),
    MONEY_INCOME MONEY CHECK (MONEY_INCOME >= 0),
    PERSONAL_ID CHAR(16) DEFAULT NULL,
    GENDER CHAR(1) DEFAULT 'U', -- U- UNDEFINED, F- FEMALE, M- MALE
    AGE INT DEFAULT 0,
    EMAIL NVARCHAR(60),
    COUNTRY INT FOREIGN KEY REFERENCES DBO.COUNTRY(ID) NOT NULL,
    DEPARTMENT INT FOREIGN KEY REFERENCES DBO.DEPARTMENT(ID) DEFAULT NULL,
    CITY INT FOREIGN KEY REFERENCES DBO.CITY(ID) DEFAULT NULL,
    BASERECIBIDA_NAME NVARCHAR(255),
    BASERECIBIDA_ID INT,
    [DATE] DATETIME DEFAULT GETDATE(),
    WHO_DO CHAR(100) NOT NULL, -- USER WHO DO LAST MODIFICATION
    [ACTION] NVARCHAR(15) CHECK ([ACTION]='DEL' OR [ACTION]='INS')
)
CREATE TABLE
NIC.STATUS_CREDEX
(
    ID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
    [NAME] NVARCHAR(50) UNIQUE,
    [DESCRIPTION] NVARCHAR(255),
    APROVE BIT DEFAULT 0,
    INPROCESS BIT DEFAULT 0,
    REJECT BIT DEFAULT 0
)
CREATE TABLE 
NIC.CREDEX
(
    CLIENT INT PRIMARY KEY FOREIGN KEY REFERENCES DBO.CLIENT(ID) NOT NULL,
    STATUS_CREDEX INT FOREIGN KEY REFERENCES NIC.STATUS_CREDEX(ID) DEFAULT NULL,
)
CREATE TABLE
NIC.CREDEX_LOG
(
    CLIENT INT FOREIGN KEY REFERENCES DBO.CLIENT(ID) NOT NULL,
    STATUS_CREDEX INT FOREIGN KEY REFERENCES NIC.STATUS_CREDEX(ID) DEFAULT NULL,
)
CREATE TABLE 
DBO.CARRIER
(
    ID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
    [NAME] NVARCHAR(30) UNIQUE NOT NULL,
    ACTIVE BIT DEFAULT 1,
    CALLABLE BIT DEFAULT 1
)
CREATE TABLE 
DBO.CARRIER_PREFIX
(
    PREFIX INT PRIMARY KEY NOT NULL,
    CARRIER INT FOREIGN KEY REFERENCES DBO.CARRIER(ID) DEFAULT NULL
)
CREATE TABLE 
DBO.PHONES
(
    PHONE INT PRIMARY KEY NOT NULL,
    CLIENT INT FOREIGN KEY REFERENCES DBO.CLIENT(ID) NULL, -- PUEDE SER NULL CUANDO SE DETECTA QUE EL NUMERO NO PERTENECE A ESA PERSONA
    PREFIX INT NULL,
    CARRIER INT FOREIGN KEY REFERENCES DBO.CARRIER(ID) DEFAULT NULL,
    IS_OWNER_CONFIRMED BIT NOT NULL DEFAULT 0,
    BASERECIBIDA_NAME NVARCHAR(255),
    BASERECIBIDA_ID INT,
    LAST_UPDATE DATETIME DEFAULT GETDATE(),
    WHO_DO CHAR(100) NOT NULL -- USER WHO DO LAST MODIFICATION
)
CREATE TABLE 
DBO.PHONES_LOG
(
    ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    PHONE INT FOREIGN KEY REFERENCES DBO.PHONES(PHONE) NOT NULL,
    CLIENT INT FOREIGN KEY REFERENCES DBO.CLIENT(ID) NULL,
    CARRIER INT FOREIGN KEY REFERENCES DBO.CARRIER(ID) NULL,
    IS_OWNER_CONFIRMED BIT NOT NULL,
    BASERECIBIDA_NAME NVARCHAR(255),
    BASERECIBIDA_ID INT,
    [DATE] DATETIME DEFAULT GETDATE(),
    WHO_DO CHAR(100) NOT NULL, -- USER WHO DO LAST MODIFICATION
    [ACTION] NVARCHAR(15) CHECK ([ACTION]='DEL' OR [ACTION]='INS')
)
CREATE TABLE 
VICI.CAMPAIGN
(
    ID VARCHAR(8) PRIMARY KEY NOT NULL,
    COUNTRY INT FOREIGN KEY REFERENCES DBO.COUNTRY(ID) NOT NULL,
    [NAME] NVARCHAR(50) NOT NULL,
    [DESCRIPTION] NVARCHAR(255) NULL,
    DATE_START DATE NULL,
    DATE_END DATE NULL,
    [STATUS] BIT DEFAULT 1 -- 0 - INACTIVE, 1- ACTIVE
)
CREATE TABLE
VICI.CALLABLE_CAMPAIGN
(
    CAMPAIGN VARCHAR(8) FOREIGN KEY REFERENCES VICI.CAMPAIGN(ID) NOT NULL,
    CARRIER INT FOREIGN KEY REFERENCES DBO.CARRIER(ID) NOT NULL,
    PRIMARY KEY (CAMPAIGN,CARRIER)
)
CREATE TABLE 
VICI.DIAL_LOG
(
    PHONE INT FOREIGN KEY REFERENCES DBO.PHONES(PHONE) NOT NULL,
    CAMPAIGN VARCHAR(8) FOREIGN KEY REFERENCES VICI.CAMPAIGN(ID) NOT NULL,
    V_LIST INT,
    V_LEAD INT,
    [DATE] DATETIME,
    USER_EXT INT,
    [USER_NAME] NVARCHAR(100),
    [STATUS] CHAR(10)
)
CREATE TABLE 
NIC.BANK
(
    ID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
    [NAME] NVARCHAR(30) UNIQUE NOT NULL,
    ACTIVE BIT DEFAULT 1
)
CREATE TABLE 
NIC.CARD
(
    ID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
    CLIENT INT FOREIGN KEY REFERENCES DBO.CLIENT(ID) NOT NULL,
    BANK INT FOREIGN KEY REFERENCES NIC.BANK(ID) NOT NULL,
    IS_CREDIT BIT DEFAULT 0,
    IS_DEBIT BIT DEFAULT 0,
    COLOR NVARCHAR(100) DEFAULT 'UNKNOW',
    ACTIVE BIT DEFAULT 1,
    BASERECIBIDA_NAME NVARCHAR(255),
    BASERECIBIDA_ID INT,
    LAST_UPDATE DATETIME DEFAULT GETDATE(),
    WHO_DO CHAR(100) NOT NULL, -- USER WHO DO LAST MODIFICATION
)
CREATE TABLE 
NIC.CARD_LOG
(
    ID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
    [CARD] INT FOREIGN KEY REFERENCES NIC.CARD(ID) NOT NULL,
    CLIENT INT FOREIGN KEY REFERENCES DBO.CLIENT(ID) NOT NULL,
    BANK INT FOREIGN KEY REFERENCES NIC.BANK(ID) NOT NULL,
    IS_CREDIT BIT,
    IS_DEBIT BIT,
    COLOR NVARCHAR(100),
    ACTIVE BIT,
    BASERECIBIDA_NAME NVARCHAR(255),
    BASERECIBIDA_ID INT,
    [DATE] DATETIME DEFAULT GETDATE(),
    WHO_DO CHAR(100) NOT NULL, -- USER WHO DO LAST MODIFICATION
    [ACTION] NVARCHAR(15) CHECK ([ACTION]='DEL' OR [ACTION]='INS')
)
CREATE TABLE
NIC.WORKPLACE
(
    ID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
    [NAME] NVARCHAR(30) UNIQUE NOT NULL,
    ACTIVE BIT DEFAULT 1
)
CREATE TABLE 
NIC.JOB
(
    ID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
    CLIENT INT FOREIGN KEY REFERENCES DBO.CLIENT(ID) NOT NULL,
    WORKPLACE INT FOREIGN KEY REFERENCES NIC.WORKPLACE(ID) NOT NULL,
    SALARY MONEY CHECK (SALARY >= 0),
    ACTIVE BIT DEFAULT 1,
    UPDATED DATE DEFAULT GETDATE()
)