INSERT INTO GOLKII_KNOWLEDGE.DBO.COUNTRY VALUES ('NICARAGUA','NI')
GO
INSERT INTO GOLKII_KNOWLEDGE.DBO.CLIENT
(
    FULL_NAME,
    FIRST_NAME,
    MIDDLE_NAME,
    LASTNAME_1,
    LASTNAME_2,
    [ADDRESS],
    MONEY_INCOME,
    PERSONAL_ID,
    GENDER,
    AGE,
    EMAIL,
    COUNTRY,
    DEPARTMENT,
    CITY,
    BASERECIBIDA_NAME,
    BASERECIBIDA_ID,
    LAST_UPDATE,
     WHO_DO
)
SELECT 
    CONCAT(PrimerNombre,SPACE(1),SegNombre,SPACE(1),PrimerApellido,SPACE(1),SegApellido),
    PrimerNombre,
    SegNombre,
    PrimerApellido,
    SegApellido,
    NULL,
    0,
    LTRIM(RTRIM(cedulaEstract)),
    'U',
    0,
    NULL,
    '1',
    NULL,
    NULL,
    'REFCOMERCIAL.DBO.INFOPADRON2010',
    ID,
    GETDATE(),
    'ADMIN'
FROM REFCOMERCIAL.DBO.INFOPADRON2010 
-- ORDER BY ID
-- OFFSET 0 ROWS
-- FETCH NEXT 10 ROWS ONLY

GO
UPDATE  GOLKII_KNOWLEDGE.DBO.CLIENT
SET AGE = NIC.GET_AGE_FROM_CEDULA(PERSONAL_ID)