 -- DROP TABLE #TEMP_TELEFONOS
-- SELECT * FROM BasesRecibidas.SYS.tables ORDER BY create_date DESC
WITH 
CTE_DB
AS (
    select 
        LTRIM(RTRIM([NOMBRE DEL CLIENTE ])) AS NOMBRE,
        LTRIM(RTRIM(REPLACE(CEDULA,'-',''))) AS CEDULA,
        LTRIM(RTRIM(REPLACE(TEL2,'-',''))) AS TEL1,
        LTRIM(RTRIM(REPLACE(TEL3,'-',''))) AS TEL2,
        LTRIM(RTRIM(REPLACE(TEL4,'-',''))) AS TEL3,
        LTRIM(RTRIM(REPLACE(TEL5,'-',''))) AS TEL4,
        LTRIM(RTRIM(REPLACE(TEL6,'-',''))) AS TEL5,
        DATO
    from BasesRecibidas.dbo.DB_25062019
),
CTE_TELEFONOS
AS (
    SELECT     
        NOMBRE,
        CEDULA,
        REPLACE(REPLACE(TEL,'*',''),'+','') AS TEL,
        DATO,
        ROW_NUMBER() OVER(PARTITION BY NOMBRE,CEDULA ORDER BY CEDULA) AS TelNo
    FROM CTE_DB
    UNPIVOT
    (  
        TEL FOR TELEFONOS IN (TEL1,TEL2,TEL3,TEL4,TEL5)
    ) PVT
)

SELECT * 
INTO #TEMP_TELEFONOS
FROM CTE_TELEFONOS 
ORDER BY CEDULA

DELETE FROM #TEMP_TELEFONOS WHERE TEL NOT LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'

SELECT 
DISTINCT NOMBRE,CEDULA 
INTO #TEMP_PERSONA
FROM #TEMP_TELEFONOS;

WITH
CTE_PERSONA_SIN_CEDULA
AS (
    SELECT * FROM #TEMP_TELEFONOS WHERE CEDULA IS NULL
)

SELECT B.Telefono,C.*
FROM CTE_PERSONA_SIN_CEDULA A
INNER JOIN GOLKIIDATA.DBO.Telefonos B ON A.TEL = B.Telefono 
INNER JOIN GOLKIIDATA.dbo.Persona C ON B.IdPersonas = C.IdPersona

SELECT * FROM #TEMP_TELEFONOS WHERE CEDULA IS NULL

DROP TABLE #TEMP_TELEFONOS
DROP TABLE #TEMP_PERSONA






