
WITH CTE_PERSONA
AS (
    select 
        DISTINCT
        A.[0010801880006U] AS CEDULA,
        A.[Fabiola Raquel Sanchez Olivarez] AS NOMBRE
    from BasesRecibidas.dbo.VENTAS_EN_DOLIBAR_20190626 A
),
CTE_INSS
AS (
SELECT 
    DISTINCT 
    CASE 
        WHEN B.CEDULA IS NOT NULL
            THEN B.CEDULA COLLATE DATABASE_DEFAULT
            ELSE A.CEDULA COLLATE DATABASE_DEFAULT
    END AS CEDULA, 
    CASE 
        WHEN B.NOMBRE IS NOT NULL
            THEN B.NOMBRE COLLATE DATABASE_DEFAULT
            ELSE A.NOMBRE COLLATE DATABASE_DEFAULT
    END AS NOMBRE 
    FROM CTE_PERSONA                    A
    LEFT JOIN REFCOMERCIAL.DBO.infoINSS B ON A.CEDULA COLLATE DATABASE_DEFAULT = B.CEDULA COLLATE DATABASE_DEFAULT
),
CTE_LAST_INSS
AS (
    SELECT A.*,
        MAX(B.ID) AS INSS_ID
    FROM CTE_INSS A
    LEFT JOIN REFCOMERCIAL.DBO.infoINSS B ON A.CEDULA COLLATE DATABASE_DEFAULT = B.CEDULA COLLATE DATABASE_DEFAULT
    GROUP BY A.NOMBRE, A.CEDULA
),
CTE_DATA
AS (
    SELECT  A.NOMBRE,
            A.CEDULA,
            B.SALARIO,
            B.DOMI_ASE AS [DOMICILIO]
    FROM  CTE_LAST_INSS A
    LEFT JOIN REFCOMERCIAL.DBO.infoINSS B ON A.INSS_ID = B.ID
),
CTE_JOIN_TELEFONOS_RECIBIDOS
AS (
    SELECT  A.*,
            CAST(B.F4 AS INT) TEL1,
            CAST(B.F5 AS INT) TEL2
    FROM CTE_DATA A
    LEFT JOIN BasesRecibidas.dbo.VENTAS_EN_DOLIBAR_20190626 B ON A.CEDULA = B.[0010801880006U]
),
CTE_PIVOTED
AS (
    SELECT NOMBRE,CEDULA,SALARIO,DOMICILIO,TELEFONOS
    FROM CTE_JOIN_TELEFONOS_RECIBIDOS  A
    UNPIVOT ( TELEFONOS FOR TELNO IN ([TEL1],[TEL2])) PVT
),
CTE_PESONAS_BASECONTROL
AS (
    SELECT A.* 
    FROM BaseControl.DBO.Persona A
    INNER JOIN CTE_PIVOTED B ON A.CEDULA = B.CEDULA
),
CTE_TELEFONOS_BASECONTROL
AS(
    SELECT DISTINCT
        B.Cedula,
        A.Telefono,
        B.Departamento
    FROM BaseControl.DBO.Telefonos A
    INNER JOIN CTE_PESONAS_BASECONTROL B ON A.IdPersona = B.IdPersona 
),
CTE_FULL_TELS
AS(
    SELECT DISTINCT 
        A.NOMBRE,
        A.CEDULA,
        A.DOMICILIO,
        B.Departamento,
        A.SALARIO,
        CASE
            WHEN A.TELEFONOS IS NULL 
                THEN B.Telefono
                ELSE A.TELEFONOS
        END AS TEL
    FROM CTE_PIVOTED  A
    LEFT JOIN CTE_TELEFONOS_BASECONTROL B ON A.CEDULA = B.Cedula
),
CTE_COUNT_TEL
AS ( 
    SELECT 
        A.*,
        ROW_NUMBER() OVER(PARTITION BY CEDULA ORDER BY TEL) AS N
    FROM CTE_FULL_TELS A
)
SELECT 
    P.NOMBRE,
    P.CEDULA,
    P.DOMICILIO,
    P.Departamento,
    P.SALARIO,
    P.[1] AS TEL1,
    P.[2] AS TEL2,
    P.[3] AS TEL3
 FROM CTE_COUNT_TEL A
PIVOT (MAX(A.TEL) FOR A.N IN ([1],[2],[3])) P
-- WHERE P.Departamento = 'MANAGUA'
