IF OBJECT_ID('tempdb.dbo.#VICI_USER_TIME') IS NOT NULL
DROP TABLE #VICI_USER_TIME
GO
CREATE TABLE #VICI_USER_TIME
(
    [USER] INT,
    [USER_NAME] NVARCHAR(100),
    CALL_STATUS NVARCHAR(10),
    PAUSE_CODE NVARCHAR(10),
    PAUSE_TIME INT,
    WAITING_TIME INT,
    TALKING_TIME INT,
    DISPO_TIME INT,
    DEADCALL_TIME INT
)
DECLARE @QUERY NVARCHAR(MAX)
SET @QUERY = [REPORTS].[GET_VICI_USERTIME_GENERAL] ('2019-09-03','2019-09-03')
EXEC(@QUERY)
-- GENERAL
SELECT 
    [USER],
    [USER_NAME],
    SUM(PAUSE_TIME) AS PAUSE_TIME,
    SUM(WAITING_TIME) AS WAITING_TIME,
    SUM(TALKING_TIME) AS TALKING_TIME,
    SUM(DISPO_TIME) AS DISPO_TIME,
    SUM(DEADCALL_TIME) AS DEADCALL_TIME
FROM #VICI_USER_TIME
GROUP BY [USER],[USER_NAME];
-- PAUSES
WITH CTE_PAUSES
AS(
    SELECT 
        [USER],
        USER_NAME,
        PAUSE_CODE,
        PAUSE_TIME
    FROM #VICI_USER_TIME
    WHERE PAUSE_CODE IS NOT NULL
)
SELECT 
    P.*
FROM CTE_PAUSES
PIVOT(SUM(PAUSE_TIME) FOR PAUSE_CODE IN ([DCMX],[LOGIN],[BAN],[SUP],[REF],[PW]))P;
-- TALK TIME
WITH CTE_TALK
AS(
    SELECT 
        [USER],
        USER_NAME,
        CALL_STATUS,
        TALKING_TIME
    FROM #VICI_USER_TIME
)
SELECT 
    P.*
FROM CTE_TALK
PIVOT(SUM(TALKING_TIME) FOR CALL_STATUS IN ([CLV],[DCMX]))P

