
WITH 
CTE_BASE_RECIBIDA
AS(
    SELECT 
        A.NOMBRE COLLATE DATABASE_DEFAULT AS NOMBRE,
        C.Nombre AS NOMBRE_GOLKII,
        A.TELEFONO,
        C.IdPersona
    FROM BASE_CREDEX_ELIEZER_31072019 A
    LEFT JOIN GOLKIIDATA.DBO.TELEFONOS B ON A.TELEFONO = B.TELEFONO
    LEFT JOIN GOLKIIDATA.DBO.Persona C ON B.IdPersonas = C.IdPersona
),
CTE_GOLKIIDATA
AS (
    SELECT B.*
    FROM CTE_BASE_RECIBIDA A
    INNER JOIN GOLKIIDATA.DBO.Persona B ON A.IdPersona = B.IdPersona
    WHERE A.NOMBRE_GOLKII LIKE '%'+REPLACE(A.NOMBRE,' ','%')+'%'
),
CTE_TARJETAS
AS (
    SELECT C.IdPersona,B.Banco, 
    ROW_NUMBER() OVER(PARTITION BY C.IdPersona ORDER BY C.IdPersona)N
    FROM GOLKIIDATA.DBO.Tarjetas A
    INNER JOIN GOLKIIDATA.DBO.Bancos B ON A.IdBanco = B.IdBanco
    INNER JOIN CTE_GOLKIIDATA C ON C.IdPersona = A.IdPersona
),
CTE_TARJETAS_PIVOTED
AS (
    SELECT 
        IdPersona,
        [1] AS TARJETA1,
        [2] AS TARJETA2,
        [3] AS TARJETA3    
    FROM CTE_TARJETAS
    PIVOT(MAX(BANCO) FOR N IN ([1],[2],[3])  )P
)
SELECT 
    A.NOMBRE,
    A.TELEFONO,
    B.Cedula,
    B.Domicilio,
    B.Salario,
    C.TARJETA1,
    'LINEA ACTIVA' AS STATAUS_CREDEX

FROM CTE_BASE_RECIBIDA A
LEFT JOIN CTE_GOLKIIDATA B ON A.IdPersona = B.IdPersona
LEFT JOIN CTE_TARJETAS_PIVOTED C ON B.IdPersona = C.IdPersona
