USE GOLKIIDATA
GO
CREATE SCHEMA FEEDBACK
GO
CREATE TABLE FEEDBACK.PERSONA(
    IDP INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
    NOMBRE NVARCHAR(100) NOT NULL,
    CEDULA CHAR(14)
)
CREATE TABLE FEEDBACK.TELEFONO(
    ID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
    IDP INT FOREIGN KEY REFERENCES FEEDBACK.PERSONA(IDP),
    TELEFONO CHAR(8) CHECK(TELEFONO LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]' )
)
GO
CREATE PROCEDURE FEEDBACK.ADD_FEEDBACK_PERSONA
(
    @NOMBRE NVARCHAR(100) ,
    @CEDULA CHAR(14)
)
AS BEGIN 
    
END 
GO