-- 
--  LOGICA PARA PROCESAR LAS PERSONAS QUE NO TIENEN EL PATRON DE CEDULA NACIONAL
-- 
-- 



CREATE TABLE ForeignPeople
(
    IDPERSONA INT PRIMARY KEY FOREIGN KEY REFERENCES PERSONA (IDPERSONA) NOT NULL,
    CEDULA NVARCHAR(100),
    NOMBRE NVARCHAR(MAX)
)
GO
CREATE TRIGGER PERSONA_AI_INSERT_FOREIGNPEOPLE
ON PERSONA
AFTER INSERT
AS BEGIN 
    INSERT INTO ForeignPeople
    SELECT  A.IdPersona,
            A.Cedula,
            A.Nombre
    FROM inserted A
    WHERE A.Cedula NOT LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][a-Z]'
    AND CEDULA IS NOT NULL
END