USE AUTOMATOR

/*
SELECT * FROM dbo.CAMPAIGN
SELECT * FROM dbo.LIST
SELECT * FROM dbo.PROFILE
SELECT * FROM dbo.PROFILE_BANCOS
SELECT * FROM dbo.PROFILE_DEP

UPDATE PROFILE SET STATE = 1
DELETE FROM LIST

EXEC ADD_CAMPAIGN 'EFNI','Campaña de Venta de Equipos Financiados Nicaragua','EFNI'
EXEC ADD_CAMPAIGN 'NICTRAV','Campaña de Citacion para Nicaragua Travel','NT'
EXEC ADD_PROFILE 'EFNI','EFNI Leon Chinandega Credex','12000',NULL,0,1
EXEC ADD_DEP_PROFILE 1,1 -- CHINANDEGA
EXEC ADD_DEP_PROFILE 2,1 -- LEON
EXEC ADD_BANK_PROFILE 3,1 --FICOHSA
EXEC ADD_BANK_PROFILE 4,1 --LAFISE
EXEC ADD_BANK_PROFILE 5,1 --BANPRO



EXEC AUTO_LIST 'EFNI'

*/

SELECT * FROM CAMPAIGN
SELECT * FROM PROFILE
SELECT * FROM LIST

SELECT * FROM PROFILE A
INNER JOIN CAMPAIGN B ON A.CAMPAIGN = B.CAMPAIGN_ID






-- DECLARACION DE VARIABLES
DECLARE @LIST_NAME NVARCHAR(MAX)
DECLARE @LIST_ID NVARCHAR(50)
-- INICIALIZACION DE VARIABLES
SELECT @LIST_ID = LTRIM(RTRIM(CAMPAIGN)) FROM PROFILE WHERE PROFILE_ID = 1
SET @LIST_NAME = @LIST_ID
-- CONTRUCCCION SEGUN DEPARTAMENTOS
SELECT  @LIST_ID += '_'+B.Abreviatura,
        @LIST_NAME += '_'+B.Departamento
    FROM PROFILE_DEP A
    INNER JOIN GOLKIIDATA.DBO.DEPARTAMENTO B ON A.PDEP = B.IdDepartamento
-- CONSTRUCCION SEGUN FILTROS
SELECT 
    -- FILTRO SALARIO MINIMO
    @LIST_ID += 
    CASE
        WHEN A.SALARIO_MIN != 0 THEN '_SMIN'+FORMAT(A.SALARIO_MIN/1000,'N1')+'K' 
        ELSE ''
    END,
    @LIST_NAME += 
    CASE
        WHEN A.SALARIO_MIN != 0 THEN '_SMIN'+FORMAT(A.SALARIO_MIN,'N0')+''
        ELSE '' 
    END,
    -- FILTRO SALARIO MAXIMO
    @LIST_ID += 
    CASE
        WHEN A.SALARIO_MAX != 0 AND A.SALARIO_MAX IS NOT NULL THEN '_SMAX'+FORMAT(A.SALARIO_MAX/1000,'N1')+'K' 
        ELSE ''
    END, 
    @LIST_NAME += 
    CASE
        WHEN A.SALARIO_MAX != 0 AND A.SALARIO_MAX IS NOT NULL THEN '_SMAX'+FORMAT(A.SALARIO_MAX,'N1')+'K' 
        ELSE ''
    END,
    -- FILTRO FORCE CREDEX
    @LIST_ID += 
    CASE
        WHEN A.FORCE_CREDEX != 0 THEN '_CDX' 
        ELSE ''
    END, 
    @LIST_NAME += 
    CASE
        WHEN A.FORCE_CREDEX != 0 THEN '_CREDEX' 
        ELSE ''
    END,
    -- FILTRO FORCE TC
    @LIST_ID += 
    CASE
        WHEN A.FORCE_TC != 0 THEN '_TC' 
        ELSE ''
    END, 
    @LIST_NAME += 
    CASE
        WHEN A.FORCE_TC != 0 THEN '_TARJETA' 
        ELSE ''
    END
FROM PROFILE A
WHERE PROFILE_ID = 1

SET @LIST_ID +=  '_'+ REPLACE(CONVERT(VARCHAR(8), GETDATE(), 3),'/','')
SET @LIST_NAME +=  '_'+ REPLACE(CONVERT(VARCHAR(8), GETDATE(), 3),'/','')

SELECT * FROM PROFILE
PRINT @LIST_ID
PRINT @LIST_NAME

go
EXEC AUTO_LIST 'EFNI'

EXEC  UPLOAD_LEAD_FOR_LIST 'EFNI','1'