                                                       --
DECLARE @QUERY NVARCHAR(MAX)                                                    --
SELECT @QUERY = GOLKIIDATA.DBO.QUERY_PHONES_ALREADY_CALLED ();                  --
CREATE TABLE #PHONES (PHONE INT)                                                --
SET @QUERY = 'INSERT INTO #PHONES '+@QUERY                                      --
EXEC (@QUERY);    



WITH CTE_RECIBIDA
AS(
    SELECT
    ID,
    NOMBRE COLLATE DATABASE_DEFAULT AS NOMBRE,
    CEDULA COLLATE DATABASE_DEFAULT AS CEDULA,
    TEL1,
    TEL2,
    TEL3,
    CIUDAD  COLLATE DATABASE_DEFAULT AS CIUDAD
    FROM BasesRecibidas.DBO.BASE_SAMIR_BOACO
),
CTE_UNP
AS(
    SELECT * FROM CTE_RECIBIDA
    UNPIVOT(TELEFONOS FOR TELEFONO IN (TEL1,TEL2,TEL3))U
    WHERE U.TELEFONOS NOT LIKE '2%'
),
CTE_CLEAN
AS(
    SELECT * FROM CTE_UNP A
    LEFT JOIN #PHONES B ON A.TELEFONOS = B.PHONE
    WHERE B.PHONE IS NULL
),
CTE_COUNTER
AS(
    SELECT 
    A.ID,
    A.NOMBRE,
    A.CEDULA,
    A.CIUDAD,
    A.TELEFONOS,
    ROW_NUMBER() OVER (PARTITION BY ID ORDER BY TELEFONOS)N
    FROM CTE_CLEAN A
)
SELECT * FROM CTE_COUNTER
PIVOT (MAX(TELEFONOS) FOR N IN ([1],[2],[3]))P