

WITH
CTE_BASE
AS (
    SELECT 
    CLIENTE COLLATE DATABASE_DEFAULT CLIENTE,
    STR(TELEFONO,8) AS TELEFONO1,
    STR(TELEFONO1,8) AS TELEFONO2,
    STR(TELEFONO2,8) AS TELEFONO3,
    REPLACE(CEDULA,'-','') COLLATE DATABASE_DEFAULT  CEDULA,
    SALARIO,
    DEPARTAMENTO COLLATE DATABASE_DEFAULT DEPARTAMENTO,
    MUNICIPIO COLLATE DATABASE_DEFAULT  MUNICIPIO,
    BANCO COLLATE DATABASE_DEFAULT BANCO
    FROM BasesRecibidas.DBO.JOHNNY_BANPRO_23082019 A
),
CTE_UNPVT_BASE
AS(
    SELECT 
    CLIENTE,CEDULA,SALARIO,DEPARTAMENTO,MUNICIPIO,BANCO,TELEFONOS
    FROM CTE_BASE
    UNPIVOT(TELEFONOS FOR TELEFONO IN (TELEFONO1,TELEFONO2,TELEFONO3))UP
),
CTE_ALREADY_CALLED
AS (
    SELECT * FROM CTE_UNPVT_BASE A
    INNER JOIN EFNI.DBO.Telefono B ON A.TELEFONOS = B.EFNI_Telefono
    WHERE B.FechaLlamada >= DATEADD(MONTH,-3,GETDATE())
),
CTE_NO_LLAMADOS
AS(
    SELECT A.*,
    SUBSTRING (A.TELEFONOS,1,4) PREFIJO
    FROM CTE_UNPVT_BASE A 
    LEFT JOIN CTE_ALREADY_CALLED B ON A.TELEFONOS = B.TELEFONOS
    WHERE B.TELEFONOS IS NULL
    AND A.TELEFONOS NOT LIKE '2%'
),
CTE_PREFIJOS
AS (
    SELECT 
        A.*,
        ROW_NUMBER() OVER(PARTITION BY A.CEDULA ORDER BY A.CEDULA) N
    FROM CTE_NO_LLAMADOS A
    INNER JOIN GOLKIIDATA.DBO.Prefijos B ON A.PREFIJO = B.Prefijo
    WHERE B.Operadora = 'MOVISTAR'
)
,
CTE_PIVOT_NO_LLAMADOS
AS(
    SELECT 
    CLIENTE,
    CEDULA,
    SALARIO,
    DEPARTAMENTO,
    MUNICIPIO,
    BANCO,
    [1] TELEFONO1,
    [2] TELEFONO2,
    [3] TELEFONO3
    FROM CTE_PREFIJOS
    PIVOT(MAX(TELEFONOS) FOR N IN([1],[2],[3]))P
),
CTE_DATA
AS(
    SELECT A.*
    FROM CTE_PIVOT_NO_LLAMADOS A
)


-- SELECT A.DEPARTAMENTO,COUNT(*) NUM FROM CTE_DATA A
-- LEFT JOIN GOLKIIDATA.DBO.Departamento B ON A.DEPARTAMENTO = B.Departamento
-- WHERE B.DEPARTAMENTO NOT IN ('LEON','CHINANDEGA')
-- GROUP BY A.DEPARTAMENTO,B.IdDepartamento 
-- ORDER BY B.IdDepartamento



SELECT * FROM CTE_DATA
WHERE DEPARTAMENTO NOT IN ('MANAGUA')