
WITH
CTE_BASE
AS(
    SELECT 
        CEDULA COLLATE DATABASE_DEFAULT CEDULA,
        NOMBRES COLLATE DATABASE_DEFAULT CLIENTE,
        DEPARTAMENTO COLLATE DATABASE_DEFAULT DEPARTAMENTO,
        MUNICIPIO COLLATE DATABASE_DEFAULT MUNICIPIO,
        DOMICILIO COLLATE DATABASE_DEFAULT DOMICILIO,
        SALARIO,
        CAST(TELEFONO AS INT) TELEFONO1,
        CAST(TELEFONO1 AS INT) TELEFONO2,
        'FICOHSA' BANCO,
        ID,
        'JOHNNY_FICOHSA_23082019' BASE
    FROM BASESRECIBIDAS.DBO.JOHNNY_FICOHSA_23082019
    WHERE SALARIO > 9000
),
CTE_CLEANING_1
AS(
    SELECT DISTINCT 
    ID,
    BASE,
    TELEFONO  ,
    CEDULA,
    CLIENTE,
    DEPARTAMENTO,
    MUNICIPIO,
    DOMICILIO,
    salario,
    BANCO
    FROM CTE_BASE
    UNPIVOT(TELEFONO FOR TELNO IN (TELEFONO1,TELEFONO2))UP
    WHERE TELEFONO LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'
)
,CTE_CLEANER
AS(
    SELECT A.* ,
    SUBSTRING(CAST(A.TELEFONO AS CHAR(8)),1,4) PREFIJO
    FROM CTE_CLEANING_1 A
    LEFT JOIN EFNI.DBO.Telefono B ON A.TELEFONO = B.EFNI_Telefono
    WHERE A.TELEFONO NOT LIKE '[1|2]%'
    OR (
        B.FechaLlamada >= DATEADD(MONTH,-3,GETDATE()) 
        and B.FechaLlamada<= '2019-08-25'
    )
),
CTE_OPERADORA
AS(
    select A.*
    from CTE_CLEANER A
    INNER JOIN GOLKIIDATA.DBO.Prefijos B ON A.PREFIJO  = B.Prefijo 
    -- WHERE B.Operadora = 'Claro'
),
CTE_COUNTER
AS(
    SELECT 
    A.*,
    ROW_NUMBER()OVER(PARTITION BY ID ORDER BY ID) N
    FROM CTE_OPERADORA A
)
,
CTE_PIVOT
AS(
    SELECT 
        ID,
        BASE,
        CEDULA,
        CLIENTE,
        DEPARTAMENTO,
        MUNICIPIO,
        DOMICILIO,
        SALARIO,
        BANCO,
        MAX([1]) TEL1,
        MAX([2]) TEL2
    FROM CTE_COUNTER
    PIVOT(MAX(TELEFONO) FOR N IN ([1],[2]))P
    GROUP BY ID,
    BASE,
        CEDULA,
        CLIENTE,
        DEPARTAMENTO,
        MUNICIPIO,
        DOMICILIO,
        SALARIO,
        BANCO
)
-- -- MENU
-- SELECT A.DEPARTAMENTO,COUNT(A.ID) FICOHSA 
-- FROM CTE_PIVOT A 
-- LEFT JOIN GOLKIIDATA.DBO.Departamento B ON A.DEPARTAMENTO = B.Departamento
-- GROUP BY A.DEPARTAMENTO,B.IdDepartamento
-- ORDER BY B.IdDepartamento

-- -- TIRAJE - LEON (4)
-- SELECT 
--     *
-- FROM CTE_PIVOT 
-- WHERE DEPARTAMENTO = 'LEON'
-- ORDER BY CEDULA
-- OFFSET 4000 ROWS
-- FETCH NEXT 2000 ROWS ONLY


-- --  TIRAJE - CHINANDEGA (3)
-- SELECT 
--     *
-- FROM CTE_PIVOT 
-- WHERE DEPARTAMENTO = 'CHINANDEGA'
-- ORDER BY CEDULA
-- OFFSET 2000 ROWS
-- FETCH NEXT 2000 ROWS ONLY



-- --  TIRAJE - MASAYA (1)
-- SELECT 
--     *
-- FROM CTE_PIVOT 
-- WHERE DEPARTAMENTO = 'MASAYA'
-- ORDER BY CEDULA
-- OFFSET 0 ROWS
-- FETCH NEXT 500 ROWS ONLY



-- --  TIRAJE - GRANADA (1)
-- SELECT 
--     *
-- FROM CTE_PIVOT 
-- WHERE DEPARTAMENTO = 'GRANADA'
-- ORDER BY CEDULA
-- OFFSET 0 ROWS
-- FETCH NEXT 500 ROWS ONLY



--  TIRAJE - RIVAS (1)
-- SELECT 
--     *
-- FROM CTE_PIVOT 
-- WHERE DEPARTAMENTO = 'RIVAS'
-- ORDER BY CEDULA
-- OFFSET 0 ROWS
-- FETCH NEXT 1000 ROWS ONLY

--  TIRAJE - MANAGUA
SELECT 
    *
FROM CTE_PIVOT 
WHERE DEPARTAMENTO = 'MANAGUA'
ORDER BY CEDULA
OFFSET 000 ROWS
FETCH NEXT 2000 ROWS ONLY